export const ALERT = "ALERT";
export const REFETCH_CHATS = "REFETCH CHATS";
export const NEW_ATTACHMENT = "NEW_ATTACHMENT";
export const NEW_MESSAGE_ALERT = "NEW_ATTACHMENT_ALERT";
export const NEW_REQUEST = "NEW_REQUEST";
